name: Update Submodules

on:
  #push:
  #  branches:
  #    - main
  #schedule:
  #  - cron: '0 0 * * *'  # 每天UTC时间0:00执行
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Submodules
        run: |
          git config --global user.email "avkiller2012@gmail.com"
          git config --global user.name "avkiller"
          git submodule update --init --recursive
          git submodule update --recursive --remote
          git add .
          git commit -m "Update submodules"
          git push
